"""followers

Revision ID: 739af53e60c9
Revises: 3aae868e8f4f
Create Date: 2018-04-03 15:09:33.167000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '739af53e60c9'
down_revision = '3aae868e8f4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
